version: '3.8'
services:

  dnd-telegram-air:
    build:

      context: "${PWD}"
      dockerfile: build/air/Dockerfile
    container_name: app-air
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - build/.env
    volumes:
      - ./:/app-air

  dnd-telegram:
    image: golang:1.21-alpine
    build:
      context: "${PWD}"
      dockerfile: build/default/Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - build/.env
    volumes:
      - ./:/app

  db:
    image: postgres:alpine
    restart: always
    container_name: db
    env_file:
      - build/.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
